name: keypress_simulator_example
description: Demonstrates how to use the keypress_simulator plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bot_toast: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hotkey_manager: ^0.1.0
  keypress_simulator:
    path: ../
  preference_list: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
