name: keypress_simulator
description: A new flutter plugin project.
version: 0.1.0
homepage: https://github.com/leanflutter/keypress_simulator

platforms:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: KeypressSimulatorPlugin
      windows:
        pluginClass: KeypressSimulatorPlugin

